version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: minhaimagem/app:latest
    container_name: fome-agricultura-app
    ports:
      - 8080:8080
    volumes:
      - app-data:/app/data
    working_dir: /app

volumes:
  app-data:
